server:
  port: 8768

#配置日志
logging:
  level:
    root: info
    com.clouddo: debug


spring:
  data:
    mongodb:
      uri: mongodb://root:Charsming619@192.168.1.91:27017/file_database
  datasource:
    name: AIDB
    url: jdbc:mysql://192.168.1.91:8066/cloud_file?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Charsming619
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    druid:
#     监控后台账号和密码
      stat-view-servlet:
        login-username: admin
        login-password: charsming619

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000