
#配置日志
logging:
  level:
    root: info
    com.clouddo.monitor: debug
cloud:
  monitor:
    push:
#      推送规则
      cron: 0 0 0 1/1 * ?
    error:
#      连续多少次无法连接报错
      limit: 5

spring:
  datasource:
    name: cloud_monitor_db
    url: jdbc:sqlserver://charsming.f3322.org:1433;DatabaseName=cloud_monitor
    username: sa
    password: Charsming619
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    druid:
#     监控后台账号和密码
      stat-view-servlet:
        login-username: admin
        login-password: charsming619

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
#      quartz数据源配置
      quartz:
        name: cloud_quartz_db
        url: jdbc:sqlserver://charsming.f3322.org:1433;DatabaseName=cloud_monitor
        username: sa
        password: Charsming619
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20