#配置日志
logging:
  level:
    root: info
    com.clouddo: debug

spring:
  datasource:
    name: systemDB
    url: jdbc:sqlserver://charsming.f3322.org:1433;DatabaseName=framework
    username: sa
    password: Charsming619
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

    druid:
#     监控后台账号和密码
      stat-view-servlet:
        login-username: admin
        login-password: charsming619

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000